# Code used to rerun the extraction 
# Vinicius Tonetti - vrtonetti@ufscar.br

# packages

library(terra)
library(sf)

# cleaning directory 
rm(list = ls())

# Considering only Atlantic Forest municipalities

AF <- st_read("D:/__PESSOAL/Vinicius_T/Limite Mata Atlantica/bioma_MA_IBGE_250mil/bioma_MA_IBGE_250mil.shp")
mun <- st_read("D:/__PESSOAL/Vinicius_T/municipios_Brasil/BR_Municipios_2023/BR_Municipios_2023.shp")
mun_WGS <- st_transform(mun, st_crs(AF))

# Municipalities that intersect AF 

mun_AF_WGS <- mun_WGS[st_intersects(mun_WGS, AF, sparse = F), ]

# Writing vector

st_write(mun_AF_WGS, "D:/__PESSOAL/Vinicius_T/municipios_Brasil/BR_Municipios_2023/mun_AF_WGS.shp")



## Cropping Annual reg raster --------------------------------------------------

AF <- vect("D:/__PESSOAL/Vinicius_T/Limite Mata Atlantica/bioma_MA_IBGE_250mil/bioma_MA_IBGE_250mil.shp")

annual_rast <- rast(c("D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen11_1ha.tif",
                      "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen12_1ha.tif",
                      "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen13_1ha.tif",
                      "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen14_1ha.tif",
                      "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen15_1ha.tif",
                      "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen16_1ha.tif",
                      "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen17_1ha.tif",
                      "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen18_1ha.tif",
                      "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen19_1ha.tif",
                      "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen20_1ha.tif",
                      "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/regen21_1ha.tif"))

dir <- "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/"

obj_name <- paste0("annual_reg_", 11:21)

for (i in 1:length(names(annual_rast))) {
  raster <- mask(crop(annual_rast[[i]], AF), AF)
  terra::writeRaster(raster, paste(dir, obj_name[i], "AF.tif", sep = ""),
                     gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)
}


## Calculating total regeneration (including what did not persist)

dir <- "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF"

setwd(dir)
annual_reg_stack <- rast(list.files(dir, pattern = "AF.tif"))
annual_reg_stack_sum <- sum(annual_reg_stack, na.rm = T)


#terra::writeRaster(annual_reg_stack_sum, paste(dir, "annual_reg_stack_sum.tif", sep = "/"),
#                   gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)


# Converting values higher than 1 to 1

annual_reg_stack_sum_0_1 <- terra::ifel(annual_reg_stack_sum %in% c(2,3), 1, annual_reg_stack_sum)
plot(annual_reg_stack_sum_0_1)

#terra::writeRaster(annual_reg_stack_sum_0_1, paste(dir, "all_reg.tif", sep = "/"),
#                   gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)

## Calculating total deforestation

reg_11_21 <- rast("D:/__PESSOAL/Vinicius_T/raster_pacto/_reg_11_21_AF.tif")

total_defo <- annual_reg_stack_sum_0_1 - reg_11_21

#terra::writeRaster(total_defo, paste(dir, "total_defo.tif", sep = "/"),
#                   gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)




# Estimating annual reg that did not persist until 2023 ------------------------
################################################################################

# cleaning directory 
rm(list = ls())

dir <- ("D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/")
setwd(dir)

#stack with annual reg raster
annual_rast_AF <- terra::rast(list.files(dir, pattern = "AF.tif"))

obj_name <- paste0("annual_reg_", 11:21)

reg_11_21 <- rast("D:/__PESSOAL/Vinicius_T/raster_pacto/_reg_11_21_AF.tif")

reg11_21_pixel02 <- terra::ifel(reg_11_21 == 1, 2, reg_11_21) # Reg 2011 - 2021 were converted to pixel values = 2

#terra::writeRaster(reg11_21_pixel02, paste(dir, "reg11_21_pixel02.tif", sep = ""),
#                   gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)

# Rasters generated by the lines below were checked in QGis, as almost all other rasters generated through this code

for (i in 1:length(names(annual_rast_AF))){
  annual_reg_summed <- annual_rast_AF[[i]] + reg11_21_pixel02
  annual_reg_did_not_persist <- terra::ifel(annual_reg_summed %in% c(2,3), 0, annual_reg_summed) # pixel values = 2 and 3 converted to zero.
  terra::writeRaster(annual_reg_did_not_persist, paste(dir, obj_name[i], "_did_not_persist.tif", sep = ""),
                     gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)
}



################################################################################
# Converting CRS to calculate area ---------------------------------------------
################################################################################

# cleaning directory 
rm(list = ls())

# TRYING TO CONVERT TO ALBERS SIRGAS 2000, DID NOT WORK ------------------------

#albers_sirgas2000 <- "+proj=aea +lat_1=-5 +lat_2=-30 +lat_0=-18 +lon_0=-54 +x_0=0 +y_0=0 +datum=SAD69 +units=m +no_defs"
# +proj=aea  - Projeção Albers Equal Area
# +lat_1=-5  - primeiro paralelo padrão (próximo ao norte da Mata Atântica)
# +lat_2=-30 - segundo paralelo padrão, próximo ao sul da Mata Atlantica
# +lat_0=-18 - Latitude de origem, próximo ao centro da Mata Atlantica
# +lon_0=-54 - Meridiano central do Brasil
# +datum=SIRGAS2000 - Datum Geodésico oficial do Brasil

dir <- "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/"


# Converting to Albers SAD 69 EPSG 102033


# Reg 2011 - 2021 that persisted until 2023

reg_11_21 <- rast("D:/__PESSOAL/Vinicius_T/raster_pacto/_reg_11_21_AF.tif")


# Testing converted methods "near" and "mode" and comparing to the original data in WGS84

# Based on visual inspection, the method "near" seems more accurate, 
# especially for small and linear forest patches


reg_11_21_AlbersSAD69 <- terra::project(reg_11_21, "ESRI:102033", method = "near")

terra::writeRaster(reg_11_21_AlbersSAD69, paste(dir, "reg_11_21_AlbersSAD69_near.tif", sep = ""),
                   gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)


#reg_11_21_AlbersSAD69 <- terra::project(reg_11_21, "ESRI:102033", method = "mode")

#terra::writeRaster(reg_11_21_AlbersSAD69, paste(dir, "reg_11_21_AlbersSAD69_mode.tif", sep = ""),
#                   gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)



# Loop to convert CRS of all raster --------------------------------------------

# cleaning directory 
rm(list = ls())

dir <- "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/"

setwd(dir)
all_rast_files <- terra::rast(list.files(dir, pattern = ".tif"))
obj_names <- paste(gsub(".tif", "", list.files(dir, pattern = ".tif")), "_ALBERS", sep = "")

dir <- "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/"

# Loop to convert and save files

for(i in 1:length(names(all_rast_files))){
assign(obj_names[i], terra::project(all_rast_files[[i]], "ESRI:102033", method = "near"))
terra::writeRaster(
  get(obj_names[i]),
  paste0(dir, obj_names[i], ".tif", sep = ""),
  gdal=c("COMPRESS=DEFLATE", "TFW=YES"),
  overwrite = T)
}


# Converting MB 2010 to Albers -------------------------------------------------

mb_2010_only_forest <- rast("D:/__PESSOAL/Vinicius_T/MapBiomas_Col_09/brasil_coverage_2010_AF_forest_only.tif")

mb_2010_only_forest_ALBERS <- terra::project(mb_2010_only_forest, "ESRI:102033", method = "near")

#terra::writeRaster(mb_2010_only_forest_ALBERS, "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/mb_2010_only_forest_ALBERS.tif",
#                   gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)



################################################################################
# Calculating areas for raster in Albers format
################################################################################

library(terra)

# cleaning directory 
rm(list = ls())

dir <- "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/"

setwd(dir)
all_rast_files <- terra::rast(list.files(dir, pattern = "ALBERS.tif"))
obj_names <- paste(gsub(".tif", "", list.files(dir, pattern = ".tif")), "_AREA", sep = "")


# Creating raster with all pixel values = 1. With this raster calculate the area of each pixel,
# and then multiply by binary rasters (0 - 1)

#raster_one <- terra::ifel(all_rast_files[[1]] == 0, 1, all_rast_files[[1]])
#raster_one_area <- mask(cellSize(raster_one, unit = "m"), raster_one)

#terra::writeRaster(raster_one_area, paste(dir, "raster_one_area.tif", sep = ""),
#                   gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)



# Loop to calculate areas

raster_one_area <- rast("D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/raster_albers_SAD69_AREA/raster_one_area.tif")


dir <- "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/raster_albers_SAD69_AREA/"

for(i in 1:length(names(all_rast_files))){
  assign(obj_names[i], raster_one_area * all_rast_files[[i]])
  terra::writeRaster(
    get(obj_names[i]),
    paste0(dir, obj_names[i], ".tif", sep = ""),
    gdal=c("COMPRESS=DEFLATE", "TFW=YES"),
    overwrite = T)
}

# MB 2010 forest only area -----------------------------------------------------

mb_2010_only_forest_ALBERS_AREA <- cellSize(mb_2010_only_forest_ALBERS, unit = "m")

mb_2010_only_forest_ALBERS_AREA <- mb_2010_only_forest_ALBERS * mb_2010_only_forest_ALBERS_AREA


#terra::writeRaster(mb_2010_only_forest_ALBERS_AREA, "D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/raster_albers_SAD69_AREA/mb_2010_only_forest_ALBERS_AREA.tif",
#                   gdal=c("COMPRESS=DEFLATE", "TFW=YES"), overwrite = T)



################################################################################
######## Extracting areas for Municipalities polygons
################################################################################

# Converting Municipalities shape to Albers

library(terra)
library(raster)
library(sf)
library(exactextractr)

# cleaning directory 
rm(list = ls())

#mun_af <- vect("D:/__PESSOAL/Vinicius_T/municipios_Brasil/BR_Municipios_2023/mun_AF_WGS.shp")
#mun_af_ALBERS <- project(mun_af, "ESRI:102033")
#writeVector(mun_af_ALBERS, "D:/__PESSOAL/Vinicius_T/municipios_Brasil/BR_Municipios_2023/mun_AF_ALBERS.shp")


mun_af <- sf::st_read("D:/__PESSOAL/Vinicius_T/municipios_Brasil/BR_Municipios_2023/mun_AF_ALBERS.shp")

# Extracting reg 11-21 to Municipalities ---------------------------------------
# ------------------------------------------------------------------------------

reg_11_21 <- raster::raster("D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/raster_albers_SAD69_AREA/reg_11_21_ALBERS_AREA.tif")

# I compared the results of extractions using exact_extract() with rasters in QGis and it makes sense
area_reg_11_21_mun <- exactextractr::exact_extract(reg_11_21, mun_af, "sum")

ncol(mun_af[,]) #14
mun_af[,15] <- round((area_reg_11_21_mun/10000), 2)
colnames(mun_af)[15] <- "r11_21"


# Extracting total regeneration (also considering what was subsequently lost)---
# ------------------------------------------------------------------------------

total_reg <- raster::raster("D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/raster_albers_SAD69_AREA/all_reg_ALBERS_AREA.tif")

total_reg <- exactextractr::exact_extract(total_reg, mun_af, "sum")

ncol(mun_af[,]) #15
mun_af[,16] <- round((total_reg/10000), 2)
colnames(mun_af)[16] <- "tt_reg"


# Extracting total deforestation of secondary forest ---------------------------
# ------------------------------------------------------------------------------

total_defo <- raster::raster("D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/raster_albers_SAD69_AREA/total_defo_ALBERS_AREA.tif")

total_defo <- exactextractr::exact_extract(total_defo, mun_af, "sum")

ncol(mun_af[,]) #16
mun_af[,17] <- round((total_defo/10000), 2)
colnames(mun_af)[17] <- "tt_defo"


# Extracting forest area 2010 --------------------------------------------------
# ------------------------------------------------------------------------------

forest_2010 <- raster::raster("D:/__PESSOAL/Vinicius_T/raster_pacto/Tiles Reg 11 - 20 Pacto-20250308T211602Z-001/Tiles Reg 11 - 20 Pacto/annual_reg_AF/raster_albers_SAD69/raster_albers_SAD69_AREA/mb_2010_only_forest_ALBERS_AREA.tif")


forest_2010 <- exactextractr::exact_extract(forest_2010, mun_af, "sum")

ncol(mun_af[,]) #17
mun_af[,18] <- round((forest_2010/10000), 2)
colnames(mun_af)[18] <- "f_2010"


# Writing vector with areas
#sf::st_write(mun_af, "D:/__PESSOAL/Vinicius_T/municipios_Brasil/BR_Municipios_2023/mun_AF_ALBERS_AREA.shp", delete_dsn = T)

sum(data.frame(mun_af[,"r11_21"])[,"r11_21"])

# ------------------------------------------------------------------------------





